services:
  exam-prep:
    container_name: exam-prep
    image: ghcr.io/kosmolito/exam-prep:latest
    ports:
      - "8080:8080"

  # To use your own questions, uncomment and adjust the lines below:
  # exam-prep:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./my-questions:/questions
  #   environment:
  #     - QUESTIONS_FILE=/questions/questions.yaml
